Fix msb indices and transfer script
The original index creation statement failed with:

listenbrainz_ts=> CREATE INDEX messybrainz_data_ndx ON messybrainz.submissions (lower(recording), lower(artist_credit), lower(release), lower(track_number), duration);
ERROR:  index row size 2784 exceeds btree version 4 maximum 2704 for index "messybrainz_data_ndx"
DETAIL:  Index row references tuple (549197,1) in relation "submissions".
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.

For now, create separate index on each column to workaround.

Also, since we have a UNIQUE index in place on the table now, use it
to avoid duplicates from the transfer script (it currently duplicates
the last transferred row on the next run).