Fix timestamp in test setup
All the tests from test_dumps_manager.py file were failign with a timestamp-related issue, thrown by this setup utility:

AttributeError: 'decimal.Decimal' object has no attribute 'timestamp'

Not exactly sure why we are receiving Decimal objects now, but reversing the logic here to check for datetime instance instead of checking for int or float instance